### ISSUE TITLE
Missing Element with Grib 2 files

### ISSUE THREAD

**Issue by silv2015** [0x1mason/GribApi.NET#13]
Hi! 

First I want to tell you that this project looks very promising! Good Work!

In our project, we are already use GDAL and it's C# wrapper but we are looking for another library to load our grib 1 and 2 files.

I have a Grib 2 files (GFS.grb2) in which I have 4 elements that we call Channels: 
Temperature
U component of Winds
V component of winds
Total Precipitation

I can read all channels except V component of winds.

It does work for all my Grib 1 files.

I cannot attach any files, but if you need more info (except I cannot send you the grib file!) please let me know!

If we can load all our Grib files with your library, we can make the switch and it will simplify a lot our work here! :)

**Comment by 0x1mason** [comment]
@silv2015 Thanks for trying the library! I will look into this and see if I can reproduce the issue.

I just released a new version, though I have no reason to think it will solve your problem.

**Comment by 0x1mason** [comment]
This works for me using v0.6.0:

``` csharp
            using(GribFile file = new GribFile(@".\TestData\Pacific.wind.7days.grb"))
            {
                var vComp = file.Where(m => m.Name.Contains("V V-component of wind m s**-1")).First();

                foreach (var val in vComp.GeoSpatialValues)
                {
                    Console.WriteLine("Lat: {0} Lon: {1} Val: {2}", val.Latitude, val.Longitude, val.Value);
                }
            }
```

[Here's the file](https://onedrive.live.com/redir?resid=CC5B0865353E559!1033&authkey=!AI_LCWk0STM-0GA&ithint=file%2cgrb) I used.

**Comment by 0x1mason** [comment]
If that ^ doesn't work for you, can you explain what you mean by "doesn't work"? Are you getting an exception? If so, what does the exception say?

**Comment by silv2015** [comment]
Hi 0x1mason!

Thanks for the answer, I downloaded your file and will give it a try

I will have another try with my file and send you what I mean by 'doesn't work'

it does not give me any exception, it's just kind of skip it.

Thanks again

**Comment by silv2015** [comment]
Here I have the result...

If I load your file, yes it works:
0:[u] "U U-component of wind m s**-1" (instant):regular_ll:surface 1:fcst time 6 hrs :from 2015-09-02 1200
1:[v] "V V-component of wind m s**-1" (instant):regular_ll:surface 1:fcst time 6 hrs :from 2015-09-02 1200

But If I load my file (.grb2) here what I have:
0:[2t] "Temperature" (instant):regular_ll:heightAboveGround 2:fcst time 0 hrs :from 2015-10-26 1200
1:[10u] "u-component of wind" (instant):regular_ll:heightAboveGround 10:fcst time 0 hrs :from 2015-10-26 1200
2:[tp] "Total precipitation" (accum):regular_ll:surface 0:fcst time 99-102 hrs :from 2015-10-26 1200
3:[2t] "Temperature" (instant):regular_ll:heightAboveGround 2:fcst time 102 hrs :from 2015-10-26 1200
4:[10u] "u-component of wind" (instant):regular_ll:heightAboveGround 10:fcst time 102 hrs :from 2015-10-26 1200
5:[tp] "Total precipitation" (accum):regular_ll:surface 0:fcst time 102-105 hrs :from 2015-10-26 1200

I should have something for the V component of winds

But like I said, if I take any .grb (not .grb2), it works

Could it be related to Grib2 file?

**Comment by 0x1mason** [comment]
You could be right, though I thought the file I used was GRIB 2, despite
the extension.

Can you see the v-component messages in GDAL, degrib, etc? I'm sure you've
confirmed it already, but worth asking.

**Comment by silv2015** [comment]
Hi 0x1mason!

I can see the component with GDAL no problem, here is an output I copy from a test:

```
    [0] "GRIB_COMMENT=Temperature [K]"  string
    [1] "GRIB_ELEMENT=TMP"  string
    [2] "GRIB_FORECAST_SECONDS=0 sec"   string
    [3] "GRIB_PDS_PDTN=0"   string
    [4] "GRIB_PDS_TEMPLATE_NUMBERS=0 0 2 0 81 0 0 0 1 0 0 0 0 103 0 0 0 0 2 255 0 0 0 0 0"  string
    [5] "GRIB_REF_TIME=  1445860800 sec UTC"    string
    [6] "GRIB_SHORT_NAME=2-HTGL"    string
    [7] "GRIB_UNIT=[K]" string
    [8] "GRIB_VALID_TIME=  1445860800 sec UTC"  string
```

---

```
    [0] "GRIB_COMMENT=u-component of wind [m/s]"    string
    [1] "GRIB_ELEMENT=UGRD" string
    [2] "GRIB_FORECAST_SECONDS=0 sec"   string
    [3] "GRIB_REF_TIME=  1445860800 sec UTC"    string
    [4] "GRIB_SHORT_NAME=10-HTGL"   string
    [5] "GRIB_UNIT=[m/s]"   string
    [6] "GRIB_VALID_TIME=  1445860800 sec UTC"  string
```

---

```
    [0] "GRIB_COMMENT=v-component of wind [m/s]"    string
    [1] "GRIB_ELEMENT=VGRD" string
    [2] "GRIB_FORECAST_SECONDS=0 sec"   string
    [3] "GRIB_REF_TIME=  1445860800 sec UTC"    string
    [4] "GRIB_SHORT_NAME=10-HTGL"   string
    [5] "GRIB_UNIT=[m/s]"   string
    [6] "GRIB_VALID_TIME=  1445860800 sec UTC"  string
```

---

```
    [0] "GRIB_COMMENT=03 hr Total precipitation [kg/(m^2)]" string
    [1] "GRIB_ELEMENT=APCP03"   string
    [2] "GRIB_FORECAST_SECONDS=356400 sec"  string
    [3] "GRIB_REF_TIME=  1445860800 sec UTC"    string
    [4] "GRIB_SHORT_NAME=0-SFC" string
    [5] "GRIB_UNIT=[kg/(m^2)]"  string
    [6] "GRIB_VALID_TIME=  1446228000 sec UTC"  string
```

---

```
    [0] "GRIB_COMMENT=Temperature [K]"  string
    [1] "GRIB_ELEMENT=TMP"  string
    [2] "GRIB_FORECAST_SECONDS=367200 sec"  string
    [3] "GRIB_REF_TIME=  1445860800 sec UTC"    string
    [4] "GRIB_SHORT_NAME=2-HTGL"    string
    [5] "GRIB_UNIT=[K]" string
    [6] "GRIB_VALID_TIME=  1446228000 sec UTC"  string
```

**Comment by 0x1mason** [comment]
Wow. Weird.

As a sanity check, I downloaded a GRIB2 file from NOAA and could see the
v-comp, so I haven't been able to repro the issue yet. Unfortunately, I'm
not going to be able to debug the issue until I can reproduce it. Here
are some options for moving forward:
1. You can find a shareable file that elicits the same behavior.
2. I can work something out with your employer in terms of signing an NDA.
3. You can send me the file privately and I will give you my word never to
   share it with anyone.

Probably best if you email me: etmillin@gmail.com

**Comment by 0x1mason** [comment]
@silv2015 

I have one more guess: the problem could be your v-comp messages use multiple fields, which isn't enabled by default. Try this:

``` csharp
using (GribFile file = new GribFile(somePath))
{
  file.Context.EnableMultipleFieldMessages = true;
  // do stuff
}
```

I haven't test this feature yet. Will do once I get appropriate test data. I also may have found some  data at the CISL site, but trying to find some that aren't 200+ GB.

Also, I just noticed there's a bug in the getter for `EnableMultipleFieldMessages`, but that shouldn't make any difference for setting it.

**Comment by 0x1mason** [comment]
Similar issue here: https://code.zmaw.de/boards/1/topics/2835

**Comment by silv2015** [comment]
Good Morning 0x1mason!

I just arrived at the office, thanks for the suggestion!

I will try it today and if I still cannot load it, I will ask how we can arrange so that you can have the file I'm using

**Comment by silv2015** [comment]
YES!!! This was it!

I added `file.Context.EnableMultipleFieldMessages = true;`

and now I can see the v component... Man I need to review the info I have on the Grib 2 format!

Thanks a lot!!!

**Comment by 0x1mason** [comment]
Woot! Glad it worked.

**Comment by 0x1mason** [comment]
Will add note to Usage section about this.

Thanks again for trying the library. Let me know if you have further issues.
