### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in Grib.Api.dll

### ISSUE THREAD

**Issue by VishmayShah** [0x1mason/GribApi.NET#18]
I Find a special case when this exception is thrown
in my code i have 

function1()
{
           try
                        {
                           using (GribFile gribFile = new GribFile(readPath))
                            {
                                    //some work
                                   gribFile.Dispose();
                                   GC.Collect();
                                   GC.WaitForPendingFinalizers();
                            }
                        }
           catch (Exception ex)
                        {
                            GC.Collect();
                            GC.WaitForPendingFinalizers();
                        }
}
function2()
{
XDocument doc=XDocument.Parse(bigxml);
}
void main()
{
function1();
function2();

}

the above main is executed and works perfectly when we have complete file,both functions are executed properly. but when readPath Files is empty(0KB), the execution goes to catch statement with error <b>This file is empty or invalid.</b>
and  function1 completes.when function2 is called and it works with big data, it is throwing 

An unhandled exception of type 'System.AccessViolationException' occurred in Grib.Api.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

function2 has not any call to gribFile

if you can replicate this case please resolve this issue, 
i am using V6.0.3,
sounds like jump to catch does not dispose gribFile completly
Thank you

**Comment by 0x1mason** [comment]
Ok, I'll take a look at it. Do you need a temporary workaround? Should be simple.

You shouldn't need to make any of those calls to GC. `Dispose` gets called when control leaves the `using` block. That in turn calls `GC::SuppressFinalize`. Furthermore, `Collect` only collects managed memory.

**Comment by 0x1mason** [comment]
For now, you can use `FileInfo::Length` to check the file length before creating the GribFile. https://msdn.microsoft.com/en-us/library/system.io.fileinfo.length(v=vs.110).aspx

**Comment by VishmayShah** [comment]
Thanks for quick resolution, i will implement it and reply .
but this is  not complete because reason of going to catch may be other
like Half downloaded file will throw error of end of file reached
Still my temp solution is done thank you

**Comment by VishmayShah** [comment]
and also dispose and collect was used just for purpose of safety nothing else

**Comment by VishmayShah** [comment]
do we have any progress in resolution of this bug?

**Comment by 0x1mason** [comment]
Not yet. Is the workaround working for you?

**Comment by VishmayShah** [comment]
Half downloaded file will throw error of end of file reached.
so not 100% working

**Comment by 0x1mason** [comment]
Ok, sorry about that. I'll try to get to it by Monday. Until then, try the following:
1. Download a hex editor, eg [HxD](http://mh-nexus.de/en/downloads.php?product=HxD)
2. Open a _complete_ file and check the very last characters. They're probably "7777". If not, check the spec for your GRIB version and find out the terminating characters for your GRIB message.
3. In addition to the `FileInfo::Length` check, read the file and check for the terminating characters.

**Comment by VishmayShah** [comment]
(37 37 37 37)7777 i am getting at last point 
grib2 is my version

**Comment by 0x1mason** [comment]
If you check for that in the downloads, that will tell you if you have a good file or not.

**Comment by 0x1mason** [comment]
Hi Vishmay,

Thanks for your patience. Can you try installing [0.6.4-beta](https://www.nuget.org/packages/Grib.Api/0.6.4-beta) and let me know if it resolves your issues?

You should get a `FileLoadException` for the empty file and a `GribApiException` for an incomplete file. You'll have to handle those exceptions as you would other valid exceptions. However, you shouldn't get any `AccessViolationExceptions`.

**Comment by 0x1mason** [comment]
@VishmayShah I'm hoping this is resolved for you. If not, let me know.

**Comment by 0x1mason** [comment]
For the actual 0.6.4 release, I've changed it so both situations throw `FileLoadException`. I also hardened the EOF check for 7777.

**Comment by VishmayShah** [comment]
i am not sure on will it work or not as i am not upgrading it now as it is used.
the origin of problem was that in try catch block if flow goes to catch block then gribapi was not disposing

so we think that not let flow go in catch, so that check for empty file if not then try to read else don’t initialize grib api
same was needed for half downloaded files (that is pending in my proj)
so FileLoadException will properly dispose grib.api for 7777 is required. is it solving it? and how to use it?

**Comment by VishmayShah** [comment]
Thank you for your great responce

**Comment by 0x1mason** [comment]
If your current solution works for you, then I would not make any changes. Here's how you would use the new changes:

``` csharp
SomeType data = null;
try
{
  using (GribFile file = new GribFile("mygrib.grb"))
  {
    // set `data`
  }
} catch (FileLoadException e)
{
  Console.WriteLine("The file is empty or incomplete: " + e.Message);
}

if (data == null)
{
  // handle failure
}
```
