### ISSUE TITLE
GeoSpatialValues() returns invalid values for latitude  

### ISSUE THREAD

**Issue by kikcorp** [0x1mason/GribApi.NET#26]
Hi All, 
I am trying to use your library in my project, but I get an error when calling GeoSpatialValues()
GeoSpatialValues() returns invalid values for latitude
Only first line of latitude is valid...  

For example i have the GRIN for 38N 06E - 56N 39E with only one message - temperature 

API returns valid GRID only for 56N latitude, for other rows latitude is invalid

{"Latitude":56.0,"Longitude":35.25,"Value":272.7,"IsMissing":false},{"Latitude":56.0,"Longitude":35.5,"Value":272.83,"IsMissing":false},{"Latitude":56.0,"Longitude":35.75,"Value":273.05,"IsMissing":false},{"Latitude":56.0,"Longitude":36.0,"Value":272.91,"IsMissing":false},{"Latitude":56.0,"Longitude":36.25,"Value":272.57,"IsMissing":false},{"Latitude":56.0,"Longitude":36.5,"Value":272.73,"IsMissing":false},{"Latitude":56.0,"Longitude":36.75,"Value":273.06,"IsMissing":false},{"Latitude":56.0,"Longitude":37.0,"Value":273.06,"IsMissing":false},{"Latitude":56.0,"Longitude":37.25,"Value":273.0,"IsMissing":false},{"Latitude":56.0,"Longitude":37.5,"Value":273.16,"IsMissing":false},{"Latitude":56.0,"Longitude":37.75,"Value":273.25,"IsMissing":false},{"Latitude":56.0,"Longitude":38.0,"Value":273.24,"IsMissing":false},{"Latitude":56.0,"Longitude":38.25,"Value":273.22,"IsMissing":false},{"Latitude":56.0,"Longitude":38.5,"Value":273.2,"IsMissing":false},{"Latitude":56.0,"Longitude":38.75,"Value":273.09000000000003,"IsMissing":false},{"Latitude":56.0,"Longitude":39.0,"Value":272.94,"IsMissing":false},{"Latitude":22.982,"Longitude":6.0,"Value":277.75,"IsMissing":false},{"Latitude":22.982,"Longitude":6.25,"Value":277.59000000000003,"IsMissing":false},{"Latitude":22.982,"Longitude":6.5,"Value":277.41,"IsMissing":false},{"Latitude":22.982,"Longitude":6.75,"Value":277.2,"IsMissing":false},{"Latitude":22.982,"Longitude":7.0,"Value":276.94,"IsMissing":false},{"Latitude":22.982,"Longitude":7.25,"Value":276.57,"IsMissing":false},{"Latitude":22.982,"Longitude":7.5,"Value":276.09000000000003,"IsMissing":false},{"Latitude":22.982,"Longitude":7.75,"Value":275.53000000000003,"IsMissing":false},{"Latitude":22.982,"Longitude":8.0,"Value":275.06,"IsMissing":false},{"Latitude":22.982,"Longitude":8.25,"Value":275.0,"IsMissing":false},{"Latitude":22.982,"Longitude":8.5,"Value":274.8,"IsMissing":false}

**Comment by 0x1mason** [comment]
Can you share your file? What should the lat be in the other cases?

**Comment by kikcorp** [comment]
incremet on grid step for each "line" of Latitude 
Example of file https://drive.google.com/file/d/0B9ZhPptl97CbLXRlVmctVHYxcFk/view

**Comment by 0x1mason** [comment]
Yes, I see what you're talking about. In the sample file, it looks like the jDirectionIncrement is the culprit. It's 33.018 which accounts for the crazy offsets you're seeing. zyGrib seems to handle it properly: http://i.imgur.com/7Pwb2Uh.png.

I'll continue to look into it and contact the grib_api team, since I don't think this has anything to do with my code.

```
Key: latitudeOfLastGridPoint Val: 10
Key: latitudeOfLastGridPointInDegrees Val: 10
Key: longitudeOfLastGridPoint Val: 20
Key: longitudeOfLastGridPointInDegrees Val: 20
Key: iDirectionIncrement Val: 0.25
Key: jDirectionIncrement Val: 33.018
```

[grib_dump.txt](https://github.com/0x1mason/GribApi.NET/files/156077/grib_dump.txt)

**Comment by 0x1mason** [comment]
What happens if you set `jDirectionIncrement` to 0.25? 

``` csharp
msg["jDirectionIncrement"].AsDouble(0.25);
```

When I did it for the first message in the sample file, I got values like this:

```
Lat: 20 Lon: 10 Val: 292.83
Lat: 20 Lon: 10.25 Val: 292.96
Lat: 20 Lon: 10.5 Val: 293.07
Lat: 20 Lon: 10.75 Val: 293.3
Lat: 20 Lon: 11 Val: 293.53
...
Lat: 19.75 Lon: 10 Val: 292.59
Lat: 19.75 Lon: 10.25 Val: 292.98
Lat: 19.75 Lon: 10.5 Val: 293.05
Lat: 19.75 Lon: 10.75 Val: 293.15
Lat: 19.75 Lon: 11 Val: 293.58
```

Hoping that provides you with a workaround.

**Comment by kikcorp** [comment]
Thank you!  
You make my day!

But i have another BUG with time of the grib message, all message have the same time as the first message time. In the file i have forecast for future dates (  

May be we need to reset another key for right value?

**Comment by kikcorp** [comment]
http://imgur.com/qc4XJa4

**Comment by 0x1mason** [comment]
Do the `validityTime` and `validityDate` keys work?

**Comment by 0x1mason** [comment]
I've got a fix. It'll be in the next release. You can figure out correct time by adding P2 or using validityTime & date.

**Comment by kikcorp** [comment]
| Do the validityTime and validityDate keys work?

Yes!  Thank you...
