### ISSUE TITLE
Lat/lon are wrong for polar stereographic grid

### ISSUE THREAD

**Issue by moab360** [0x1mason/GribApi.NET#27]
Thanks for providing this wrapper.  Once I get it up and running I'm sure it'll be super useful :)

I used NuGet to install Grib.Api in VS2015.  When I try to load a Grib file (new GribFile(...)), I get an insta-crash that i'm unable to debug into.

So I figured I'd build the dlls on my own from the source.  Grib.Api.dll builds fine but Grib.Api.Native is failing with a link error to 'grib_api.lib.lib'

I'm a bit lost so any help would be great!

Thanks
-Dan

**Comment by 0x1mason** [comment]
Regarding the insta crash, what type of app are running? What are you doing when it crashes?

**Comment by moab360** [comment]
The end goal is that this code would sit on a ASP.Net server (Azure) and at some frequency parse a set of grib files into a database.  

Until then I have it in a simple WPF app so I can validate the contents of the grib and compare values to what I'm seeing in NOAAs Climate viewer.  The app crashes when GribMessage msg = file.First() is called.

```
       OpenFileDialog openFileDialog = new OpenFileDialog();
        if (openFileDialog.ShowDialog() == true)
        {
            using (GribFile file = new GribFile(openFileDialog.FileName))
            {
                GribMessage msg = file.First(); //Crash!
            }
        }
```

In the debugger I can see that a GribFile is made, however if i try to look into it's contents while debugging I get the same crash if I enumerate the results view.

Here is the grib if you're interested.  It appears to load correctly in the NOAA grib viewer.
http://dd.weather.gc.ca/model_gem_regional/15km/grib2/00/000/CMC_reg_TCDC_SFC_0_ps15km_2016031000_P000.grib2 

Thanks for your help
-Dan

**Comment by 0x1mason** [comment]
Btw, the insta crashes are actually built into grib_api. They abort the process on a fatal error.  I've avoided hacking their library, but this is frustrating and I will probably have to.

**Comment by moab360** [comment]
I figured as much.  I didn't look through the grib_api but looking through your wrapper I assumed the crash wasn't in there 

Interesting side note.  If I run VS with admin rights then nothing seems to crash.  But the values I end up getting for Latitude and Longitude seem... off.  For example, the Longitude ranges from roughly 70 to 420.

**Comment by 0x1mason** [comment]
Regarding "offness":
Can you take a [look at this](https://github.com/0x1mason/GribApi.NET/issues/26)? About half way down I mention j/iDirectionIncrement. Check those and look for crazy values. If it's a true grid, make sure they're equal. The formula to figure the correct value is simple. If you need help, lmk.

Regarding crash:
The admin thing is interesting and you may have actually hit on something. I read something about native code, Azure, and special permissions in the manifest. I'll see what I can find. You can take a look at [this](https://github.com/0x1mason/GribApi.NET/issues/22), but I'm guessing there's an issue with permissions.

**Comment by 0x1mason** [comment]
https://msdn.microsoft.com/library/azure/gg557553.aspx#WebRole

`enableNativeCodeExecution` should be enabled by default, but you want to check.

**Comment by moab360** [comment]
re: j/iDirectionIncrement - I'm actually not seeing those keys at all...  That might explain the weirdness.  How should they be set?

re: native code -  thanks for the reference above!  I'll give that a try.

**Comment by 0x1mason** [comment]
Some how I missed this post about WPF. `GribEnvironment.Init` should cure
your ills. See #22.

**Comment by moab360** [comment]
Oh nice, that fixed the crash!  Now I don't have to boot VS with admin rights :)

**Comment by 0x1mason** [comment]
Looking at the lat/lon values now.

**Comment by 0x1mason** [comment]
Key dump for reference

[key_dump.txt](https://github.com/0x1mason/GribApi.NET/files/168213/key_dump.txt)

**Comment by 0x1mason** [comment]
This code prints lat/lons in the expected range. Can you verify you're getting wacky data?

``` csharp
int i = 0;

foreach (GeoSpatialValue val in msg.GeoSpatialValues) {
  if ((i++ > 500 && val.Longitude < 360) || val.IsMissing) { continue; }

  log(String.Format("Lat: {0} Lon: {1} Val: {2}", val.Latitude, val.Longitude, val.Value));

  if (0 == i % 20) { logBox.Refresh(); }
}

```

**Comment by moab360** [comment]
I'm just writing the values directly into a .csv (converted to xlsx so I could upload, let me know if you can't get at that)

Here is the function creating the dataset

private void OpenGRIBFile(object sender, RoutedEventArgs e)
        {
            GribEnvironment.Init();

```
        OpenFileDialog openFileDialog = new OpenFileDialog();
        if (openFileDialog.ShowDialog() == true)
        {
            GRIBOutputText.Text = "";
            GribFile file = new GribFile(openFileDialog.FileName);

            GribMessage msg = file.First();

            string WriteFileLocation = @"C:\Users\dfior\Desktop\";
            string WriteFileName = @"GeoSpatialValuesToCSV.csv";

            System.IO.StreamWriter WriteFile = new System.IO.StreamWriter(WriteFileLocation + WriteFileName);
            WriteFile.WriteLine(@"Latitude,Longitude,Value");

            foreach (GeoSpatialValue val in msg.GeoSpatialValues)
            {
                if (val.IsMissing || val.Longitude<360) { continue; }

                WriteFile.WriteLine(val.Latitude + "," + val.Longitude + "," + val.Value);
            }
            WriteFile.Close();
        }
    }
```

[GeoSpatialValuesToCSV.xlsx](https://github.com/0x1mason/GribApi.NET/files/168311/GeoSpatialValuesToCSV.xlsx)

**Comment by 0x1mason** [comment]
Bizarro. My csv comes out completely empty.

**Comment by moab360** [comment]
Hmm, I'll keep looking to see what's going on.  FYI  I'm using the NuGet version Grib.Api 0.6.3 and VS 2015

**Comment by 0x1mason** [comment]
Are you using the same file you attached above? I can't repro with 0.6.3.

Can you try this? https://www.nuget.org/packages/Grib.Api/0.6.5-beta

**Comment by moab360** [comment]
Crud, sorry I linked the wrong Grib above
http://dd.weather.gc.ca/model_gem_regional/10km/grib2/00/000/CMC_reg_TCDC_SFC_0_ps10km_2016031100_P000.grib2

**Comment by moab360** [comment]
Same results with 0.6.5-beta.  Longitudes up to 428.7.  Sorry about linking the wrong Grib above :/

**Comment by 0x1mason** [comment]
I'll ping the grib_api team. Unfortunately, I'm a software developer, not a meteorologist. I can figure out basic calculation errors, but nothing is jumping out at me.

**Comment by moab360** [comment]
Fair enough, I'm in the same boat :)  Thanks again for the help

**Comment by 0x1mason** [comment]
Waiting to hear back. Will update with support ticket info.

**Comment by 0x1mason** [comment]
Dan, if you want to track this, you can create a free account: https://software.ecmwf.int/issues/browse/SUP-1567

I did manage to find a solution for the abort/exit calls that were causing the process to terminate, so should be more pleasant to use and debug moving forward.

**Comment by 0x1mason** [comment]
@moab360 Do you know if any of the lat/lon values are correct? I was [reading this](https://nsidc.org/data/polar-stereo/ps_grids.html) and now I'm wondering if this isn't a bug, but rather the assumptions for the polar stereograph need tweaking to get the values to come out right.

**Comment by 0x1mason** [comment]
This is fixed. Will be in the next release. If you'd like a workaround sooner, let me know.

**Comment by 0x1mason** [comment]
@moab360 I failed to push the fix for this. Will do asap.

**Comment by 0x1mason** [comment]
Assuming this is resolved.
