### ISSUE TITLE
Parse 2 submessages inside one message (windU / windV)

### ISSUE THREAD

**Issue by asafHorvitz** [0x1mason/GribApi.NET#29]
Hi,

I have a message that contains 2 submessages - wind -  consists of U and V axis and both are in the same message - i am reffering to NAM grib.

in the Grib.api i see only the U axis and i cant parse the V axis

How do I parse it ?

**Comment by silv2015** [comment]
Actually it's not a problem, I had a similar situation, you just have to add 'EnableMultipleFieldMessages' after opening the file and before parsing any messages:

```
using (var file = new GribFile(ctx.GribFile))
{
    file.Context.EnableMultipleFieldMessages = true;
    ....
}
```

**Comment by asafHorvitz** [comment]
Great !!!

Thanks !!!

_From:_ Martin Brousseau [mailto:notifications@github.com]
_Sent:_ Monday, March 28, 2016 4:28 PM
_To:_ 0x1mason/GribApi.NET GribApi.NET@noreply.github.com
_Cc:_ asafHorvitz asaf@taranis.ag
_Subject:_ Re: [GribApi.NET] Parse 2 submessages inside one message (windU
/ windV) (#29)

Actually it's not a problem, I had a similar situation, you just have to
add 'EnableMultipleFieldMessages' after opening the file and before parsing
any messages:

using (var file = new GribFile(ctx.GribFile))

{

```
file.Context.EnableMultipleFieldMessages = true;

....
```

}

**Comment by silv2015** [comment]
No problem! Glad I helped!
