### ISSUE TITLE
FileIsValid rejects parsable file

### ISSUE THREAD

**Issue by jnyrup** [0x1mason/GribApi.NET#36]
I have a grib2 file from [SADIS](http://www.metoffice.gov.uk/aviation/sadis) containing information on clear air turbulence (CAT).
Parsing it with wgrib2 gives the following output
```
1:41:d=2016091400:CAT:400 mb:6 hour fcst:spatial ave
2:19534:d=2016091400:CAT:350 mb:6 hour fcst:spatial ave
3:39414:d=2016091400:CAT:300 mb:6 hour fcst:spatial ave
4:59282:d=2016091400:CAT:250 mb:6 hour fcst:spatial ave
5:80347:d=2016091400:CAT:200 mb:6 hour fcst:spatial ave
6:97389:d=2016091400:CAT:150 mb:6 hour fcst:spatial ave
7:112099:d=2016091400:CAT:400 mb:6 hour fcst:spatial max
8:142877:d=2016091400:CAT:350 mb:6 hour fcst:spatial max
9:173577:d=2016091400:CAT:300 mb:6 hour fcst:spatial max
10:203681:d=2016091400:CAT:250 mb:6 hour fcst:spatial max
11:234819:d=2016091400:CAT:200 mb:6 hour fcst:spatial max
12:261598:d=2016091400:CAT:150 mb:6 hour fcst:spatial max
```

GribApi.Net rejects the file in `FileIsValid`.
When omitting the call to `FileIsValid` the file parses without problems.

I tried to look at `FileIsValid`, but couldn't decipher the logic.
Can I send you the file?

**Comment by 0x1mason** [comment]
Yes. Attach it here or etmillin at gmail.

**Comment by 0x1mason** [comment]
Fixed. Pushed up the code. Trying to get the package on nuget, but having some network issues. Regardless, should be available soon, along with your PRs.
