### ISSUE TITLE
Support for partial downloads from NOAA Gfs

### ISSUE THREAD

**Issue by jeroendenhertog** [0x1mason/GribApi.NET#39]
Hi,

when downloading from NOAA GFS, it is possible to download only sections of GRIB files. See:
http://www.cpc.ncep.noaa.gov/products/wesley/fast_downloading_grib.html

Basically, you read the index to find the offset to download from the number of bytes to download. 

Currently, GribApi.Net will only read entire GRIB files. It is quite simple to add this functionality however, which would improve the support for NOAA GFS data.

I implemented this in Gribmessage.cs:

/// <summary>
/// Creates a GribMessage instance from a byte array, allowing to read parts of a Grib file directly
/// </summary>
/// <param name="bytes">The file.</param>
/// <param name="index">The index.</param>
/// <returns></returns>
public static GribMessage Create(byte[] bytes, int index)
{
      GribMessage msg = null;
      int err = 0;
      GCHandle pinnedArray = GCHandle.Alloc(bytes, GCHandleType.Pinned);
      IntPtr pointer = pinnedArray.AddrOfPinnedObject();
      SizeT data_len = (SizeT)bytes.Length;

      GribHandle handle = GribApiProxy.GribHandleNewFromMultiMessage(GribApiProxy.GribContextGetDefault(), out pointer, ref data_len, out err);
      
      pinnedArray.Free();

      if (err != 0)
      {
           throw GribApiException.Create(err);
      }

      if (handle != null)
      {
          msg = new GribMessage(handle, GribApiProxy.GribContextGetDefault(), index);
      }

      return msg;
}

This will require initialization of the Environement manually (GribEnvironment.Init()). May be better to include that in this function. I don't have data where the index needs to be other than 0 for testing, so never tested that part of the function. 

The above is the reason I'm not happy to do a pull request. 

I hope this makes sense. Let me know if I can help getting this functionality included.

Best regards,

Jeroen

**Comment by 0x1mason** [comment]
Sounds great. I'm prepping the 1.0 release and will get this in there.

**Comment by 0x1mason** [comment]
Can you post a file containing a partial download?

**Comment by 0x1mason** [comment]
@jeroendenhertog Can you post a file? Thaks

**Comment by 0x1mason** [comment]
Implemented
