### ISSUE TITLE
Unexpected Lat/Lon Data from NOAA Files

### ISSUE THREAD

**Issue by ericbmartin** [0x1mason/GribApi.NET#42]
I am using GribAPI.NET to access NOAA file data, for example:

[ftp://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/DF.gr2/DC.ndgd/GT.rtma/AR.conus/RT.00/ds.temp.bin](url)

When I pull out Lat and Lon from this file using the code below, I do not get any negative Lon values, but I should based on these files being of the continental US.  Is there some conversion setting or code change I need to make to get US-oriented Lat/Lon values?

`

using (GribFile gribFile = new GribFile(m_file_name))
{
	foreach (GribMessage hour in gribFile)
	{
		double[] rawValues;

		foreach (GeoSpatialValue geoLocValue in hour.GeoSpatialValues)
		{
			if (geoLocValue.IsMissing) { continue; }

			// Read and convert the Lat and Lon
			decimal lat = Math.Round(geoLocValue.Latitude.ToDecimal(), 1, MidpointRounding.AwayFromZero);
			decimal lon = Math.Round(geoLocValue.Longitude.ToDecimal(), 1, MidpointRounding.AwayFromZero);

			Console.WriteLine("{0} \t {1}", lat, lon);
		}
	}
}

`

**Comment by 0x1mason** [comment]
Are the numbers correct if you subtract 180?

**Comment by 0x1mason** [comment]
In the GRIB 2 specification, all Lon values are between 0 and 360.

**Comment by 0x1mason** [comment]
Closing. If you feel like this doesn't solve your issue, please lmk.

**Comment by ericbmartin** [comment]
Thanks for the insight, I used the code below and that seems to be working out:

decimal lon = Math.Round(180M - geoLocValue.Longitude.ToDecimal(), 1, MidpointRounding.AwayFromZero);
