### ISSUE TITLE
Giving access to grid data using the grib_fin_nearest_XXXX API

### ISSUE THREAD

**Issue by jblestang** [0x1mason/GribApi.NET#43]
What would be the recommended way to access single data point value in Grib.API ?  I've not been able to locate a function that would end calling a **grib_find_nearest_XXXX** function call, instead I've to get all the values in memory in the application before getting access to a single element which is not memory nor time efficient when processing large grib data files.

**Comment by 0x1mason** [comment]
I have not provided a wrapper for that functionality, but it is exposed in https://github.com/0x1mason/GribApi.NET/blob/master/src/GribApi.NET/Grib.Api/Interop/SWIG/GribApiProxyPINVOKE.cs

Search for "GribNearest".

If you're comfortable with pinvoke, you should be able to get it working. Here's some example C code you could use to guide you. https://software.ecmwf.int/wiki/plugins/servlet/mobile?contentId=7374682#content/view/7374682

Otherwise I can try to add this functionality.

**Comment by jblestang** [comment]
OK, thanks I'll look into this way and let you know how this is going

**Comment by jblestang** [comment]
Ok, It's working as expected !

**Comment by 0x1mason** [comment]
That's great! Can you share your code?

**Comment by jblestang** [comment]
This is the code I used 
```
public void GetNearestValue(double latitude, double longitude, GribFile gb)
        {
            Grib.Api.Interop.GribContext c = Grib.Api.Interop.SWIG.GribApiProxy.GribContextGetDefault();
            int err = 0;
            double[] outlats = { 0, 0, 0, 0 };
            double[] outlongs = { 0, 0, 0, 0 };
            double[] distances = { 0, 0, 0, 0 };
            double[] values = { 0, 0, 0, 0 };
            int[] indexes = { 0, 0, 0, 0 };

            Grib.Api.Interop.GribHandle h = Grib.Api.Interop.SWIG.GribApiProxy.GribHandleNewFromFile(c, gb, out err);
            var nearest = Grib.Api.Interop.SWIG.GribApiProxy.GribNearestNew(h, out err);
            Grib.Api.Interop.SizeT len = 0;
            if (err == 0)
            {
                Grib.Api.Interop.SWIG.GribApiProxy.GribNearestFind(nearest, h, latitude, longitude, 0, outlats, outlongs, values, distances, indexes, ref len);

            }
            Grib.Api.Interop.SWIG.GribApiProxy.GribHandleDelete(h);
            Grib.Api.Interop.SWIG.GribApiProxy.GribNearestDelete(nearest);
        }
```

It works well for data that are not compressed, but I do have large JPEG compressed data and it seems each time it is decompressing the data to get the nearest value :/

**Comment by 0x1mason** [comment]
@jblestang Can you tell at which point it's decompressing? Is it in `GribNearestFind`?

**Comment by jblestang** [comment]
From my memory this was where the decompression was happening and I was not found of their interpolation either. I'm now looking for a way to download the joeg compressed grib file then create an uncompressed version on disk rather than original grib

**Comment by 0x1mason** [comment]
I added this feature tho I'm not sure about performance.

**Comment by 0x1mason** [comment]
Do you know if this works with GribMessage handles? Seems like it should.

**Comment by 0x1mason** [comment]
This is in the latest beta
