### ISSUE TITLE
Migrating to ecCodes 

### ISSUE THREAD

**Issue by jblestang** [0x1mason/GribApi.NET#44]
Do you plan on migrating to [ecCodes](https://software.ecmwf.int/wiki/display/ECC) which is an evolution of grib_api ?

**Comment by 0x1mason** [comment]
I do not at this point. I don't use the project, do very little Windows development, and have little bandwidth atm.

If someone else were to get involved then I would be happy to do it. I have made it much simple to upgrade and work overall in the v1.0.0 branch, so perhaps that will encourage folks to get involved. (Tho I need to publish the new version)

**Comment by 0x1mason** [comment]
Looks like there's been a big jump in usage since November, so maybe I'll get some more regular contributors.
