### ISSUE TITLE
How to change any GeoSpatialValues and append message to another file?

### ISSUE THREAD

**Issue by abbaabbbaabbbbbaa** [0x1mason/GribApi.NET#45]

**Comment by 0x1mason** [comment]
There are examples of adding messages to a file in the [README](https://github.com/0x1mason/GribApi.NET/blob/master/README.md).

To edit the data, you'll want to use `msg.Values` to get the raw data and `msg.SetValues`. it's not very performant, so if you're doing this often, I'll see if there's a faster way.

Also, if you want to create new messages, IIRC you can read a file from the `GribApi/samples` and fill in the blanks.

**Comment by 0x1mason** [comment]
Please
