### ISSUE TITLE
How to crop a box and save it to another grib file

### ISSUE THREAD

**Issue by abbaabbbaabbbbbaa** [0x1mason/GribApi.NET#46]
Hi! I need crop a box and save it to another grib file... 

I execute method **msg.Box(new GeoCoordinate(59.981188, -120.177277), new GeoCoordinate(49.387815, -110.157746));** and get exception **"new GeoCoordinate(74, 40)"**

**Comment by 0x1mason** [comment]
I dropped support for boxes. I will look into adding them back.

**Comment by 0x1mason** [comment]
If you're
