### ISSUE TITLE
EnableMultipleFieldMessages Detection

### ISSUE THREAD

**Issue by IdahoSixString** [0x1mason/GribApi.NET#49]
As previously noted in #29 and #47 it seems to be a common issue to have to enable EnableMultipleFieldMessages. Maybe the when running the a similar method to FileIsValid we could detect if EnableMultipleFieldMessages needs to be set to true or not. Thoughts?

**Comment by 0x1mason** [comment]
I'm not sure how to do this. I'm considering making it the default

**Comment by 0x1mason** [comment]
@IdahoSixString I figured out how to do this. Do you have a file I can use for tests?

**Comment by 0x1mason** [comment]
@IdahoSixString @jnyrup @silv2015 Can one of you provide or refer a service that can provide a grib file that contains at least 2 messages that do not work correctly without `EnableMultipleFieldMessages` enabled? I need one to test the new auto-detection feature, but I'm having difficulty locating one.

Many thanks for your help and interest in the project.

**Comment by IdahoSixString** [comment]
[WRFPRS_NAM_00z_d01.000.zip](https://github.com/0x1mason/GribApi.NET/files/1160711/WRFPRS_NAM_00z_d01.000.zip)


@0x1mason Here you go this file will require that you have EnableMultipleFieldMessages enabled.

**Comment by 0x1mason** [comment]
@IdahoSixString Thanks.

**Comment by silv2015** [comment]
Sorry but All the files I have are at least 50mb, I can ask my service provider for a smaller file if you still need it?

**Comment by 0x1mason** [comment]
@IdahoSixString @silv2015 I ended up just enabling it by default. The grib_api docs caution against it, but several of the other wrapper libs I've seen do it and having it disabled has been a major source of confusion.

The context object is static, so trying to dis/enable dynamically could cause surprising behavior when dealing with the multiple files at the same time. Not worth.

As always, I appreciate your help.

**Comment by IdahoSixString** [comment]
@0x1mason Can you please upload your new beta package to NuGet? I only see the 1.0 beta on NuGet.

**Comment by 0x1mason** [comment]
@IdahoSixString Check now

**Comment by jnyrup** [comment]
@0x1mason beta is still listed as the neweset pre-release: https://www.nuget.org/packages/Grib.Api/

**Comment by IdahoSixString** [comment]
Still only see 1.0.0-beta.
________________________________

**Comment by 0x1mason** [comment]
@IdahoSixString @jnyrup It's definitely there now.

**Comment by IdahoSixString** [comment]
I see it there now. What happened previously?
________________________________
