### ISSUE TITLE
CallbackOnCollectedDelegate Bug

### ISSUE THREAD

**Issue by IdahoSixString** [0x1mason/GribApi.NET#50]
Managed Debugging Assistant 'CallbackOnCollectedDelegate'  occurred
  HResult=0x00000000
  Message=**Managed Debugging Assistant 'CallbackOnCollectedDelegate' :** 'A callback was made on a garbage collected delegate of type 'Grib.Api!Grib.Api.Interop.Util.GribApiNative+GribLogProc::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'

Try running something similar to 
Directory.GetFiles("PathToGribFiles").Select(x => new FileInfo(x).Select(x => new GribFile(x.FullName)).OrderBy(x => x.First().Time).ToList()

Note - You must have multiple grib2 files. 

This will reproduce the above error. 

This error can also lead to this kind of exception as well.
This can also lead to a other errors such as: 
System.AccessViolationException occurred
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Grib.Api

**For anyone else whom runs into this problem in order to get around it until the library can be fixed prior to enumerating to the next file copy out all the contents of the GribFile object that you need.**

As a final thought since this library is doing interop and using i'm assuming another third party dll. How much work would it be just to rewrite the library not to use interop but manage everything internally?

**Comment by 0x1mason** [comment]
Trying to recreate this library in pure managed code would be a totally massive and totally pointless undertaking. Afaik, grib_api is the most comprehensive and powerful set of GRIB-related tools in any language. Why not utilize that? Plus, I don't use the library anymore and only one other person has ever submitted a proper PR.

Furthermore, afaik, it's quite stable tho I can only go by the reports I receive here. The bug you're seeing is likely my error and is unrelated to interop specifically.

Can you try v1.0.0-beta and let me know if the issue still exists?

**Comment by IdahoSixString** [comment]
Accidentally closed.

However, the problem still exists in the beta as well.

**Comment by IdahoSixString** [comment]
You had mentioned you were using grib_api. I saw this post just thought I would share.

https://software.ecmwf.int/wiki/display/GRIB/Home

The ECMWF GRIB-API is an application program interface accessible from C, FORTRAN and Python programs developed for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages. A useful set of command line tools is also provided to give quick access to GRIB messages.
The latest version of GRIB edition 2 documents from the WMO can be accessed HERE

**"Starting from version 2.0.0, ecCodes is the primary GRIB encoding/decoding package used at ECMWF. Any new features for the handling of GRIBs will be only developed in ecCodes. Nevertheless GRIB-API will be maintained and new releases made publicly available to support decoding of ECMWF model output. Replacing GRIB-API with ecCodes is expected to be transparent for current GRIB-API users. In particular the "grib_" functions are included in the ecCodes library.

Users are strongly advised to start the migration process."**

**Comment by IdahoSixString** [comment]
Not sure if anyone needs this is not but as noted in my previous post you just need to copy your data out of the GribFile object prior to moving on. I just mocked up a quick dirty copy of the data I needed to get past this bug.

Depending on how big your grib files are you may or may not run into the 2gb limit on your list sizes. If you are running a 64 bit system in your App.Config you can add. 


configuration>
  runtime>
    gcAllowVeryLargeObjects enabled="true" />
  /runtime>
/configuration>

In addition, you will need to go into properties => build => uncheck Prefer 32 bit. 

        public GribFileDto ReadGribFile(string fileName)
        {
            try
            {
                GribFile gribFile = new GribFile(fileName);
                GribFileDto gribData = new GribFileDto(gribFile);

                return gribData;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                Console.WriteLine();
                return null;
            }
        }

    public class GribFileDto
    {
        public string FileName { get; private set; }
        public int MessageCount { get; private set; }

        public GribFileDto(GribFile gribFile)
        {
            FileName = gribFile.FileName;
            MessageCount = gribFile.MessageCount;
            GribMessages = gribFile.Select(x => new GribMessageDto(x)).ToList();
        }
        public List<GribMessageDto> GribMessages { get; private set; }
    }

    public class GribMessageDto
    {
        public DateTime Time { get; private set; }
        public int DatePointsCount { get; private set; }
        public string ShortName { get; private set; }
        public string LongName { get; private set; }
        public GribMessageDto(GribMessage gribMessage)
        {
            Time = gribMessage.Time;
            DatePointsCount = gribMessage.DataPointsCount;
            ShortName = gribMessage.ShortName;
            LongName = gribMessage.ToString();
            GribValues = gribMessage.Select(x => new GribValueDto(x)).ToList();
            GeoSpatialValues = gribMessage.GeoSpatialValues.ToList();
        }

        public List<GribValueDto> GribValues { get; set; }
        public List<GeoSpatialValue> GeoSpatialValues { get; private set; }
    }
    public class GribValueDto
    {
        public GribValueDto(GribValue gribValue)
        {
        }
    }

    public class GeoSpatialValueDto
    {
        public double Latitude { get; private set; }

        public double Longitude { get; private set; }

        public double Value { get; private set; }

        public GeoSpatialValueDto(GeoSpatialValue geoSpatialValue)
        {
            Latitude = geoSpatialValue.Latitude;
            Longitude = geoSpatialValue.Longitude;
            Value = geoSpatialValue.Value;
        }
    }

**Comment by 0x1mason** [comment]
@IdahoSixString I'm removing the log proc. It was never very helpful anyway.

**Comment by 0x1mason** [comment]
@IdahoSixString Is the error the same with the beta? IIRC, I disabled the logging proc in that release, so what you're describing shouldn't happen.

**Comment by 0x1mason** [comment]
This should be resolved in the latest beta 1.0.0-beta2

**Comment by 0x1mason** [comment]
@IdahoSixString Should also note that your repro case does not error for me using the new release.
