### ISSUE TITLE
Publish pre-release of Grib.Api.Native?

### ISSUE THREAD

**Issue by eriove** [0x1mason/GribApi.NET#51]
Thanks for a great library. Looking forward to version 1.0.

I'm investigating a bug, most likely something that only applies to our internal files. Would it be possible for you to publish a prerelease version of "Grib.Api.Native"? That way I can the latest source myself.

**Comment by eriove** [comment]
I got the tests running by copying files from the latest Grib.Api package before Grib.Api.native was introduced. It would still be useful to have prerelease versions though.

**Comment by 0x1mason** [comment]
Done

**Comment by 0x1mason** [comment]
https://www.nuget.org/packages/Grib.Api.Native/
