### ISSUE TITLE
Use stream instead of filename

### ISSUE THREAD

**Issue by proanalyticsdev** [0x1mason/GribApi.NET#59]
I'm implementing a custom extractor in U-SQL (Azure Data Lake Analytics) to read grib files. In U-SQL you receive a byte stream when reading the data. Are there any plans for supporting streams in addition to a filename when opening a grib file?

**Comment by eriove** [comment]
I'm not the maintainer but have faced the problem too. It seems really hard to pass a managed stream to unmanaged code and since this is a wrapper around an unmanaged component I believe this to be really hard or impossible.

I "just" check if it is a file stream and grab the file name if it is. If it isn't I create a temporary file. Kind of hacky but works in my case.

**Comment by 0x1mason** [comment]
I'll look into this

**Comment by 0x1mason** [comment]
Looks like it may be possible: https://pastebin.com/jcjHdnwz
https://msdn.microsoft.com/en-us/library/system.io.pipes.anonymouspipeserverstream.aspx

**Comment by eriove** [comment]
Wow, that would be a great addition. No more for unnecessary files on disk

**Comment by 0x1mason** [comment]
I played with this a bit and it's going to take a lot of work. Not sure when this will happen. Would welcome a PR tho :)

**Comment by 0x1mason** [comment]
Ok, I think there's an easier way to do this. You can create messages by passing bytes. So rather than messing with streams directly, you'd just pass the underlying buffer. Easy peasy (I hope)

**Comment by 0x1mason** [comment]
I've got mostly bad news on this. I've got a working implementation, but iterating multiple messages is about 6x slower than files. This will take some more work.

**Comment by 0x1mason** [comment]
I added a new API so you can create a message from an array of bytes. Not exactly what you're looking for, but as of beta 4 you can call `GribMessage.Create(myBytes, 0, GribContext.Default);`. Please play around with it and lmk if its moving in the right direction.

**Comment by 0x1mason** [comment]
The full release with have `GribStream`. It's still slower than file, but much faster than my previous tests indicated. You can let me know if it's within tolerable limits.
