### ISSUE TITLE
Rename Method Clone To Copy

### ISSUE THREAD

**Issue by IdahoSixString** [0x1mason/GribApi.NET#60]
This really isn't a clone but rather a shallow copy of the data the underlying references are the same. 

Here is a good definition of the difference between copy and clone (https://stackoverflow.com/questions/2200409/what-is-the-difference-between-copying-and-cloning)

**Comment by 0x1mason** [comment]
`Clone` is the name of the `grib_api` function it wraps (well, really `grib_handle_clone`).

**Comment by 0x1mason** [comment]
I'm inclined to leave the named unchanged, but I will at leased add more to the Intellisense docs

**Comment by IdahoSixString** [comment]
@0x1mason I believe including more intellisense docs is good.

**Comment by 0x1mason** [comment]
@IdahoSixString On second thought, I agree with your suggestion and have made the change. Thanks for pointing out that this was actually a shallow copy.
