### ISSUE TITLE
Grib.Api.Native is build against debug libraries

### ISSUE THREAD

**Issue by jnyrup** [0x1mason/GribApi.NET#62]
When running 1.0.0-beta it fails with an `TypeInitializationException`. 
procmon says that `Grib.Api.Native.dll` it looking for `MSVCP140D.dll` which as far as I can tell is debug versions of MSVC 2015 redistributables.

**Comment by 0x1mason** [comment]
Ok, thanks

**Comment by jnyrup** [comment]
Closing here, as the problem is more clearly described in #64 .
