### ISSUE TITLE
Out of range values of latitude and longitude

### ISSUE THREAD

**Issue by muteebali** [0x1mason/GribApi.NET#82]
@0x1mason  I am trying to develop an application for GIS using **GribApi.NET**. I am facing an issue, _values of latitude and longitude seem out of range_. Now, I am not sure how to scale down these values. 
As the range for latitude and longitude values should be -90 to 90 and -180 to 180 respectively, but in my case latitude and longitude values are exceptionally exceeding i.e -1360.000563
Can you please help me out, is there any way to handle this scenario or am I missing something?

**Comment by 0x1mason** [comment]
Which version are you using? Is it the latest Beta? If the beta doesn't resolve the issue, please share the file.

**Comment by muteebali** [comment]
No, its not a latest version. Its version 0.7.1.0.

**Comment by muteebali** [comment]
_I have upgraded the dll to latest Beat version (1.0.0.4), but problem is still there._
I am trying to process one of your test file (TIME), i am getting following data in **GridCoordinateValue**, which lies out of range,

**jDirectionIncrement : 33.018
iDirectionIncrement : 0.25
latitudeOfLastGridPoint : 10
longitudeOfLastGridPoint : 20
latitudeOfFirstGridPoint : 20
longitudeOfFirstGridPoint : 10
Total Data Point : 1680**

I have checked all values in **GridCoordinateValues** list, latitude values do not lie in standard nor in above range. I think so latitude values are being incremented by **jDirectionIncrement** having incorrect value.

In case of first **GribMessage** values are, 
**Latitude for GridCoordinateValues[1680] is -1300.72000000000009
Longitude for GridCoordinateValues[1680] is 20
Value for GridCoordinateValues[1680] is 301.79**

I have also tried different file but same problem occurs. I am attaching the file.
https://github.com/0x1mason/GribApi.NET/blob/master/src/GribApi.NET/Grib.Api.Tests/TestData/time.grb
I look forward forward to hearing from you.

**Comment by 0x1mason** [comment]
When I make the following change using the `time` file,
```csharp
gribMsg["jDirectionIncrement"].AsDouble(0.25);
```
I get:
```
[1680] Lat 10, Lon 20, Value 301.79
```

Does setting Dj programmatically fix the issue for you?

**Comment by 0x1mason** [comment]
Can you tell which files you're using? Are they NCEP grib1?

**Comment by muteebali** [comment]
Thanks,  its working now.

**Comment by 0x1mason** [comment]
This issue was moved to GribApiDotNet/GribApi.NET#10
