### ISSUE TITLE
Problem to identify record type 

### ISSUE THREAD

**Issue by muteebali** [0x1mason/GribApi.NET#83]
@0x1mason  How can we identify a single record in a file having different types of data (temperature, wind, humidity etc. ) either it is temperature related data or wind etc ?
Can you please help me out.

**Comment by 0x1mason** [comment]
I would recommend starting with a key dump on a sample message to see the metadata exposed by ecCodes. Here's an example result: https://github.com/0x1mason/GribApi.NET/blob/master/docs/TypicalKeyDump.md.

Using the beta, you can do `Console.Writeline(gribMsg.Dump())` or with all versions
```csharp
foreach (var kvp in gribMsg)
{
  Console.Writeline(kvp.Key + ": " + kvp.AsString());
}
```

Once you know which key you want to filter on, you can do something like
```csharp
using(GribFile file = new GribFile(@".\TestData\Pacific.wind.7days.grb"))
{
	foreach (var msg in  file.Where(m => m.ParameterName == "T Temperature K")))
        // or
        //   foreach (var msg in file.Where(m => m["parameterName"].AsString() == "T Temperature K")))
	{
		// do something
	}
}
```

**Comment by 0x1mason** [comment]
Also, if you're concerned about NOAA-related files, the next release will greatly improve the string information for units, etc. I'm adding string info for ~ 1000 message types.

**Comment by muteebali** [comment]
that`s great, should it work for all types of Temperature related data? What about wind/humidity etc. 
Can you please specify Parameter Names for each case or some other way to do it prior to know parameter name.
Secondly, is there way to know a file having singular parametric data or multi parametric?

**Comment by 0x1mason** [comment]
Here is a list of the parameters covered by eccodes:
http://apps.ecmwf.int/codes/grib/param-db

Then there are centre-specific grid definitions that you'll need to check
the centre's documentation for. I'm adding NCEP ones for grids like these
http://www.nssl.noaa.gov/projects/mrms/operational/tables.php, though I
haven't pushed those changes yet. However, no degribber can cover all the
custom grids out there. eccodes allows you to add your own definitions. I
can get you a link if you want.

In any case, `msg.Name`, `msg.ParameterName`, and `msg.ParameterUnits`,
should generally get you what you want.

>

**Comment by 0x1mason** [comment]
This issue was moved to GribApiDotNet/GribApi.NET#9
