### ISSUE TITLE
Why GRIB.net    only read the first repetition when a message repeat section 3-7 as the figure shown below?

### ISSUE THREAD

**Issue by hehuan710** [0x1mason/GribApi.NET#84]
![1](https://user-images.githubusercontent.com/21091848/29876457-6b25cce8-8dcf-11e7-88fe-4a809fff70ae.png)

**Comment by jnyrup** [comment]
What version of GribApi.Net are you using?
If it is not 1.0.0-beta4, please give it a try.

If beta4 still cannot read all sections: can you share the problematic file?

**Comment by hehuan710** [comment]
Isn't  the latest version  0.7.1?

**Comment by hehuan710** [comment]
thank you   I'll try 1.0.0-beta4

**Comment by hehuan710** [comment]
beta4 still cannot read all sections  
[Z_NWGD_C_BABJ_20170828035059_P_RFFC_SCMOC-SSM_201708280800_07203.zip](https://github.com/0x1mason/GribApi.NET/files/1265359/Z_NWGD_C_BABJ_20170828035059_P_RFFC_SCMOC-SSM_201708280800_07203.zip)

**Comment by 0x1mason** [comment]
@hehuan710 Try
```csharp
GribEnvironment.Init();
GribContext.Default.EnableMultipleFieldMessages = true;
var file = new GribFile("my/path/file.grib");
```

**Comment by 0x1mason** [comment]
I will disable this by default in the next release

**Comment by 0x1mason** [comment]
^enable by default

**Comment by hehuan710** [comment]
@0x1mason 
![qq 20170901130909](https://user-images.githubusercontent.com/21091848/29956034-d6320e1e-8f16-11e7-87a9-b963354a60bc.jpg)

**Comment by hehuan710** [comment]
@

**Comment by jnyrup** [comment]
@hehuan710 

I could reproduce the `TypeInitializtionException`
Instead of calling `GribContext.Default.EnableMultipleFieldMessages = true;`

Try this:
```
using (var file = new GribFile(path))
{
    file.Context.EnableMultipleFieldMessages = true;
}
```

@0x1mason I believe I have seen this behavior in the code before, where calling something from `GribEnvironment` or `GribContext` even after `GribEnvironment.Init()` causes a `TypeInitializtionException`.

**Comment by hehuan710** [comment]
@jnyrup     As you said, that's all right

**Comment by 0x1mason** [comment]
Fix will be in next release.
